steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello', '.']

options:
  logging: NONE
  pool:
    name: 'projects/$PROJECT_ID/locations/europe-west1/workerPools/default' # Spécifiez une région différente

images:
- 'gcr.io/$PROJECT_ID/hello'